### ISSUE TITLE
Download folder is being stripped at the wrong period.

### ISSUE THREAD

**Issue by j1nx** [OpenVoiceOS/ovos-ww-plugin-vosk#11]
The auto download of the small model en-us (http://alphacephei.com/vosk/models/vosk-model-small-en-us-0.15.zip) is wrongly be unpacked and saved as;

```/home/ovos/.local/share/vosk/vosk-model-small-en-us-0```

It strips the last two digits and period as it being the file extension which it isn't

Similar as; https://github.com/OpenVoiceOS/ovos-stt-plugin-vosk/pull/10

**Comment by JarbasAl** [comment]
fixed by #15
